### ISSUE TITLE
Move to @octokit org

### ISSUE THREAD

**Issue by wolfy1339** [octokit/openapi-webhooks#80]
In order to move this repository and it's packages to the Octokit org, as discussed in https://github.com/octokit/webhooks.js/pull/841
This will be used in the next major version of `@octokit/webhooks`

- [x] transfer repository to https://github.com/octokit
- [x] rename packages to `@octokit/openapi-webhooks`, `@octokit/openapi-webhooks-types-*` and release new versions
- [ ] create new repository `wolfy1339/openapi-webhoks-legacy`. That way https://github.com/wolfy1339/openapi-webhooks will continue to redirect to the new https://github.com/octokit/openapi-webhooks
- [ ] Install `@octokit/openapi-webhooks` as the sole dependency for `@wolfy1339/openapi-webhooks`
- [ ] Add deprecation message when used. The type packages would be kinda hard to do this
- [ ] deprecate `@wolfy1339/openapi-webhooks` and `@wolfy1339/openapi-webhooks-types-*` packages on npm
- [x] Release a new version of packages

**Comment by wolfy1339** [comment]
Ping @gr2m @nickfloyd @kfcambell Can you help out with transfering this to the Octokit org

**Comment by nickfloyd** [comment]
Hey @wolfy1339 Can you give us admin access to this repo so that we can take the first step and move this over to the octokit org?

**Comment by wolfy1339** [comment]
Sure thing

**Comment by nickfloyd** [comment]
Looks like I just got push access... just to confirm you want this to be a complete hoist and move to @octokit correct? If so I'll need access to settings as well.

**Comment by wolfy1339** [comment]
Yup, a complete move. I haven't been able to find the proper setting for giving admin access. All I can see is either inviting collaborator, or removing them.

I have searched the docs to no avail. It only refers to collaborators for personal repositories

**Comment by nickfloyd** [comment]
Ok... have you attempted to transfer ownership under settings > General > Transfer Ownership 

Then choose the `Specify and organization or username`  radial button

Then enter in `octokit` and click `I understand, transfer this repository`

**Comment by wolfy1339** [comment]
That doesn't work.
> You don’t have the permission to create public repositories on octokit

**Comment by wolfy1339** [comment]
This is all I see under "Manage Access"
![image](https://github.com/wolfy1339/openapi-webhooks/assets/4595477/f0148d5d-27ef-4ad5-8407-12474072e6c1)

**Comment by nickfloyd** [comment]
When you click on `General` what do you see?

**Comment by wolfy1339** [comment]
![image](https://github.com/wolfy1339/openapi-webhooks/assets/4595477/2379577d-b34d-4b10-a790-0a99fa95e087)

**Comment by nickfloyd** [comment]
Cool... you should now be able to follow the [steps above](https://github.com/wolfy1339/openapi-webhooks/issues/80#issuecomment-1948758487).

**Comment by wolfy1339** [comment]
Those steps are still not working, with the same message
> You don’t have the permission to create public repositories on octokit

**Comment by wolfy1339** [comment]
Giving someone admin rights in a personal repository is not supported
Bummer 😞
https://github.com/community/community/discussions/108527#discussioncomment-8495427

**Comment by nickfloyd** [comment]
> Those steps are still not working, with the same message
> 
> > You don’t have the permission to create public repositories on octokit

Let me have a look at your permissions on the octokit org. Sorry for all of this trouble @wolfy1339.

**Comment by nickfloyd** [comment]
Ok.. someone smarter than me came up with a workaround - I've added you to the [octokit-transfers](https://github.com/orgs/octokit-transfers) org.  You'll have admin access there and then we can move the repo to it's final destination under octokit.  So sorry for all of this complexity... hopefully we can get everything moved.

**Comment by wolfy1339** [comment]
Alright that works! Moved it

**Comment by wolfy1339** [comment]
It seems some things need tweaking, the release process failed. Seems like the token possibly isn't set
https://github.com/octokit/openapi-webhooks/actions/runs/7936287389/job/21671231791

**Comment by nickfloyd** [comment]
> It seems some things need tweaking, the release process failed. Seems like the token possibly isn't set https://github.com/octokit/openapi-webhooks/actions/runs/7936287389/job/21671231791

I believe [this](https://github.com/octokit/openapi-webhooks/pull/81) should fix it

**Comment by gr2m** [comment]
Really great work on this, thank you @wolfy1339!!
